# Generated by Django 3.0.4 on 2020-03-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=128)),
                ('note', models.PositiveSmallIntegerField(null=True)),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('role', models.CharField(choices=[('AC', 'Actor'), ('DI', 'Director'), ('DE', 'Default')], default='DE', max_length=2)),
            ],
            options={
                'unique_together': {('name', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128, unique=True)),
                ('average_note', models.FloatField(blank=True, null=True)),
                ('release_date', models.DateField(null=True)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('persons', models.ManyToManyField(to='movies.Person')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Review')),
            ],
        ),
    ]
