# Generated by Django 3.0.4 on 2020-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200315_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(blank=True, to='movies.Person'),
        ),
    ]
